<?php 
require_once('DBConnection.php');
?>

<div class="content py-4">
    <div class="card border-0 shadow-sm rounded-4 overflow-hidden">
        <div class="card-header bg-white border-bottom py-3 px-4 d-flex flex-wrap justify-content-between align-items-center gap-3">
            <div>
                <h3 class="fw-bold text-dark mb-0"><span class="fa fa-boxes me-2 text-primary"></span>Product List</h3>
                <p class="text-muted small mb-0">Manage your bakery items, pricing, stock quantities, and availability.</p>
            </div>
            <div class="card-tools">
                <button class="btn btn-primary bg-gradient btn-sm px-3 py-2 rounded-pill shadow-sm" type="button" id="create_new">
                    <i class="fa fa-plus me-1"></i> Add New Product
                </button>
            </div>
        </div>
        
        <div class="card-body p-4">
            <!-- Search and Filter Section -->
            <div class="row mb-3 gap-2">
                <div class="col-md-4">
                    <input type="text" id="search_product" class="form-control rounded-3" placeholder="Search by code, name...">
                </div>
                <div class="col-md-3">
                    <select id="filter_category" class="form-select rounded-3">
                        <option value="">All Categories</option>
                        <?php
                        $cat_stmt = $conn->prepare("SELECT category_id, name FROM category_list WHERE status = 1 AND delete_flag = 0 ORDER BY name ASC");
                        if ($cat_stmt) {
                            $cat_stmt->execute();
                            $cat_result = $cat_stmt->get_result();
                            while ($cat = $cat_result->fetch_assoc()) {
                                echo '<option value="' . $cat['category_id'] . '">' . htmlspecialchars($cat['name']) . '</option>';
                            }
                            $cat_stmt->close();
                        }
                        ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <select id="filter_status" class="form-select rounded-3">
                        <option value="">All Status</option>
                        <option value="1">Popular</option>
                        <option value="0">Unpopular</option>
                    </select>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-hover align-middle border" id="product-table">
                    <thead class="table-dark text-uppercase fs-7">
                        <tr>
                            <th class="text-center py-3 px-2">No</th>
                            <th class="py-3 px-2">Code</th>
                            <th class="py-3 px-2">Category</th>
                            <th class="text-center py-3 px-2">Image</th>
                            <th class="py-3 px-2">Product Info</th>
                            <th class="text-center py-3 px-2">Price</th>
                            <th class="text-left py-3 px-2">Stock</th>
                            <th class="text-left py-3 px-2">Alert</th>
                            <th class="text-left py-3 px-2">Status</th>
                            <th class="text-center py-3 px-2">Action</th>
                        </tr>
                    </thead>
                    <tbody id="product-tbody">
                        <tr>
                            <td colspan="10" class="text-center py-4">
                                <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>Loading products...
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Pagination -->
            <nav aria-label="Page navigation" class="mt-4">
                <ul class="pagination justify-content-center" id="pagination">
                    <!-- Pagination buttons will be generated by JavaScript -->
                </ul>
            </nav>
        </div>
    </div>
</div>

<script>
$(function(){
    let currentPage = 1;
    let pageSize = 20;
    let totalPages = 1;

    // Load products on page load
    loadProducts(1);

    // Create new product
    $('#create_new').click(function(){
        uni_modal('Add New Product', "manage_product.php", 'mid-large');
    });
    
    // Search functionality
    $('#search_product').on('keyup', function(){
        currentPage = 1;
        loadProducts(1);
    });

    // Filter by category
    $('#filter_category').on('change', function(){
        currentPage = 1;
        loadProducts(1);
    });

    // Filter by status
    $('#filter_status').on('change', function(){
        currentPage = 1;
        loadProducts(1);
    });

    // Load products via AJAX with server-side pagination
    function loadProducts(page) {
        const search = $('#search_product').val();
        const category = $('#filter_category').val();
        const status = $('#filter_status').val();

        $.ajax({
            url: './get_products_data.php',
            method: 'POST',
            data: {
                page: page,
                page_size: pageSize,
                search: search,
                category: category,
                status: status
            },
            dataType: 'json',
            success: function(response) {
                if (response.success) {
                    renderProducts(response.products);
                    totalPages = response.total_pages;
                    currentPage = page;
                    renderPagination();
                } else {
                    $('#product-tbody').html('<tr><td colspan="10" class="text-center py-4 text-danger">' + response.message + '</td></tr>');
                }
            },
            error: function() {
                $('#product-tbody').html('<tr><td colspan="10" class="text-center py-4 text-danger">Error loading products. Please try again.</td></tr>');
            }
        });
    }

    function renderProducts(products) {
        let html = '';
        
        if (products.length === 0) {
            html = '<tr><td colspan="10" class="text-center py-4 text-muted fst-italic">No products found.</td></tr>';
        } else {
            products.forEach(function(row, index) {
                const stock = parseFloat(row.stock);
                const alert = parseFloat(row.alert_restock);
                const stockStatus = stock <= alert ? 
                    '<span class="badge bg-danger bg-gradient px-3 py-2 rounded-pill fs-7 shadow-sm"><i class="fa fa-exclamation-triangle me-1"></i> ' + new Intl.NumberFormat('en-US').format(stock) + '</span>' :
                    '<span class="badge bg-success bg-gradient px-3 py-2 rounded-pill fs-7 shadow-sm">' + new Intl.NumberFormat('en-US').format(stock) + '</span>';
                
                const statusBadge = parseInt(row.status) === 1 ?
                    '<span class="badge bg-primary bg-gradient px-3 py-2 rounded-pill fs-7 shadow-sm">Popular</span>' :
                    '<span class="badge bg-secondary bg-gradient px-3 py-2 rounded-pill fs-7 shadow-sm">Unpopular</span>';

                html += `
                    <tr>
                        <td class="text-center py-3 px-2 fw-semibold text-muted">${(currentPage - 1) * pageSize + index + 1}</td>
                        <td class="py-3 px-2 font-monospace text-secondary">${escapeHtml(row.product_code)}</td>
                        <td class="py-3 px-2 fw-semibold text-dark">${escapeHtml(row.cname)}</td>
                        <td class="text-center py-3 px-2">
                            <img src="${escapeHtml(row.image_path)}" alt="${escapeHtml(row.name)}" class="img-thumbnail rounded-3 shadow-sm" style="height: 45px; width: 45px; object-fit: cover;">
                        </td>
                        <td class="py-3 px-2">
                            <div class="fw-bold text-dark text-truncate" style="max-width: 220px;" title="${escapeHtml(row.name)}">
                                ${escapeHtml(row.name)}
                            </div>
                            <div class="text-muted small text-truncate" style="max-width: 220px;" title="${escapeHtml(row.description)}">
                                ${escapeHtml(row.description)}
                            </div>
                        </td>
                        <td class="py-3 px-2 text-end fw-semibold text-black">Rs. ${new Intl.NumberFormat('en-US', { minimumFractionDigits: 2 }).format(parseFloat(row.price))}</td>
                        <td class="py-3 px-2 text-center">
                            ${stockStatus}
                        </td>
                        <td class="py-3 px-2 text-center text-muted fw-semibold">${new Intl.NumberFormat('en-US').format(alert)}</td>
                        <td class="py-3 px-2 text-center">
                            ${statusBadge}
                        </td>
                        <td class="text-center py-3 px-2">
                            <div class="dropdown">
                                <button type="button" class="btn btn-outline-secondary btn-sm rounded-pill px-3 dropdown-toggle shadow-sm" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end shadow border-0 rounded-3 py-2">
                                    <li><a class="dropdown-item view_data py-2 px-3" data-id="${row.product_id}" href="javascript:void(0)"><i class="fa fa-eye text-info me-2"></i>View</a></li>
                                    <li><a class="dropdown-item edit_data py-2 px-3" data-id="${row.product_id}" href="javascript:void(0)"><i class="fa fa-edit text-primary me-2"></i>Edit</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item delete_data py-2 px-3 text-danger" data-id="${row.product_id}" data-name="${escapeHtml(row.name)}" href="javascript:void(0)"><i class="fa fa-trash text-danger me-2"></i>Delete</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                `;
            });
        }

        $('#product-tbody').html(html);
        attachEventHandlers();
    }

    function renderPagination() {
        let html = '';
        
        // Previous button
        html += `<li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                    <a class="page-link" href="javascript:void(0)" onclick="window.loadProducts(${currentPage - 1})">Previous</a>
                </li>`;
        
        // Page numbers
        let startPage = Math.max(1, currentPage - 2);
        let endPage = Math.min(totalPages, currentPage + 2);
        
        if (startPage > 1) {
            html += `<li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="window.loadProducts(1)">1</a></li>`;
            if (startPage > 2) {
                html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
            }
        }
        
        for (let i = startPage; i <= endPage; i++) {
            html += `<li class="page-item ${i === currentPage ? 'active' : ''}">
                        <a class="page-link" href="javascript:void(0)" onclick="window.loadProducts(${i})">${i}</a>
                    </li>`;
        }
        
        if (endPage < totalPages) {
            if (endPage < totalPages - 1) {
                html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
            }
            html += `<li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="window.loadProducts(${totalPages})">${totalPages}</a></li>`;
        }
        
        // Next button
        html += `<li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                    <a class="page-link" href="javascript:void(0)" onclick="window.loadProducts(${currentPage + 1})">Next</a>
                </li>`;
        
        $('#pagination').html(html);
    }

    function attachEventHandlers() {
        $('.edit_data').click(function(){
            uni_modal('Edit Product Details', "manage_product.php?id=" + $(this).attr('data-id'), 'mid-large');
        });
        
        $('.view_data').click(function(){
            uni_modal('Product Details', "view_product.php?id=" + $(this).attr('data-id'), '');
        });
        
        $('.delete_data').click(function(){
            _conf("Are you sure to delete <b>" + $(this).attr('data-name') + "</b> from Product List?", 'delete_data', [$(this).attr('data-id')]);
        });
    }

    function escapeHtml(text) {
        const map = {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#039;'
        };
        return text.replace(/[&<>"']/g, m => map[m]);
    }

    // Make loadProducts accessible globally for pagination
    window.loadProducts = loadProducts;

    function delete_data(id){
        $('#confirm_modal button').attr('disabled', true);
        $.ajax({
            url: './Actions.php?a=delete_product',
            method: 'POST',
            data: { id: id },
            dataType: 'JSON',
            error: function(err){
                console.log(err);
                alert("An error occurred. Check console for details.");
                $('#confirm_modal button').attr('disabled', false);
            },
            success: function(resp){
                if(resp && resp.status == 'success'){
                    location.reload();
                } else {
                    alert(resp.msg || "Deletion failed.");
                    $('#confirm_modal button').attr('disabled', false);
                }
            }
        });
    }
});
</script>
